# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Okan Binli
tagline: "Junior Ruby on Rails Developer"
picture: okanbinli.jpg #keep a 100x100 image inside images folder.
email: okanbinli@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My personal website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://peyloride.github.io" # the base hostname & protocol for your site
brand-color: '#e74c3c'
permalink: ':title/'

#Social Links
# Delete the lines you don't need
# about 5 elements are recomended
github_username:  peyloride
facebook_username: okanb3
twitter_username: okanbinli
linkedin_username: okanbinli
instagram_username:  okanbinli

# footer
credits: webjeda #credits on the footer
version: 1.0

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

sass:
  style: compressed

disqus-shortname: peyloride-github-io
analytics: UA-91742758-1

include: [_pages]



#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []


prose:
  rooturl: ''
  siteurl: 'http://prose.github.io/starter/'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'images'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes


gems: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]
