---
title: Okan Binli
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
tagline: Software Developer
picture: okanbinli.jpg
logo: "http://peyloride.xyz/images/logo.png"
email: okanbinli@gmail.com
description: "My personal website. I'm a Software Developer who loves to code in Ruby.
              Motocycle Rider (Bajaj Pulsar currently). Philosophical enthusiast since highscool.
              #Free and #Equal"
baseurl: ''
url: http://peyloride.xyz
brand-color: "#e74c3c"
permalink: ":title/"
github_username: peyloride
facebook_username: okanb3
twitter_username: okanbinli
linkedin_username: okanbinli
instagram_username: okanbinli
credits: webjeda
version: 1.0
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
sass:
  style: compressed
disqus-shortname: peyloride-github-io
analytics: UA-91742758-1
include:
- _pages
compress_html:
  clippings:
  - html
  - div
  - p
  - ul
  - td
  - h1
  - h2
  - h3
  - h4
  - link
  - meta
  - footer
  - nav
  - img
  - header
  - hr
  - br
  - head
  - style
  - li
  - ul
  - ol
  - time
  - main
  - script
  - title
  comments:
  - "<!-- "
  - " -->"
  endings:
  - all
  ignore:
    envs:
    - local
  blanklines: false
  profile: false
  startings: []
prose:
  rooturl: _posts
  siteurl: http://peyloride.xyz
  media: images
  ignore:
  - index.md
  - _config.yml
  - "/_layouts"
  - "/_includes"
plugins:
- jekyll-paginate
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-admin
